version: '3.4'

services:
  grpcservice:
    container_name: grpcservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80" 
      - "8001:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - grpc-network
  
  grpcclient:
    container_name: grpcclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcServiceUrl=http://grpcservice:8000"
    networks:
      - grpc-network
    depends_on:
      - grpcservice

networks:
  grpc-network:
    external: true
